import { BT1 } from "./db/BT1.db";
import { P } from "./db/P.db";

const CARDS = {
  ST1: [
    {type: 'egg',name:'Koromon', no: 1, set: 'ST1',
      colors: ['red'],
      level: 2,
    form: 'In-Training', traits: ['Lesser'],
    inherit: ['<<Your Turn>> While this Digimon has 4 or more','digivolution cards, it gets +1000 DP.']},

    {type: 'dgmn',name:'Biyomon', no: 2, set: 'ST1',
      colors: ['red','black'], 
      level: 3, 
      form: 'Rookie', attr: 'Vaccine', traits: ['Bird'],
      dp: 3, cost: 2, evoCost: [0],
      effect: [],
      inherit: ['-'] },

    {type:'dgmn', name:'Agumon', no: 3, set: 'ST1',
      colors: ['red'], 
      level: 3, 
      form: 'Rookie', attr: 'Vaccine', traits: ['Reptile'],
      dp: 2, cost: 3, evoCost: [0],
      effect: [],
      inherit: ['<<Your Turn>> This Digimon gets +1000 DP.'] },

    {type:'dgmn', name:'Dracomon', no: 4, set: 'ST1',
      colors: ['red'], 
      level: 3, 
      form: 'Rookie', attr: 'Data', traits: ['Dragon'],
      dp: 4, cost: 3, evoCost: [0],
      effect: [],
      inherit: ['-'] },

    {type:'dgmn', name:'Birdramon', no: 5, set: 'ST1',
      colors: ['red'], 
      level: 4, 
      form: 'Champion', attr: 'Vaccine', traits: ['Giant Bird'],
      dp: 5, cost: 4, evoCost: [2],
      effect: [],
      inherit: ['-']},
    {type:'dgmn', name:'Coredramon', no: 6, set: 'ST1',
      colors: ['red'], 
      level: 4, 
      form: 'Champion', attr: 'Virus', traits: ['Dragon'],
      dp: 6, cost: 5, evoCost: [2],
      effect: ['<<Blocker>>','<<When Attacking>> Lose 2 memory.'],
      inherit: ['-']},
    {type:'dgmn', name:'Greymon', no: 7, set: 'ST1',
      colors: ['red'], evoCost: [2],
      level: 4, 
      form: 'Champion', attr: 'Vaccine', traits: ['Dinosaur'],
      dp: 4, cost: 5, evoCost: [2],
      effect: [],
      inherit: ['<<Security Attack +1>>']},

    {type:'dgmn', name:'Garudamon', no: 8, set: 'ST1',
      colors: ['red'], 
      level: 5, 
      form: 'Ultimate', attr: 'Vaccine', traits: ['Birdkin'],
      dp: 7, cost: 6, evoCost: [3],
      effect: ['<<When Digivolving>> 1 of your Digimon gets +3000 DP for','the turn.'],
      inherit: ['-']},

    {type:'dgmn', name:'MetalGreymon', no: 9, set: 'ST1',
      colors: ['red'], 
      level: 5, 
      form: 'Ultimate', attr: 'Vaccine', traits: ['Cyborg'],
      dp: 7, cost: 7, evoCost: [3],
      effect: [],
      inherit: ['<<Your Turn>> When this Digimon is blocked, gain','3 memory.']},

    {type:'dgmn', name:'Phoenixmon', no: 10, set: 'ST1',
      colors: ['red'], 
      level: 6, 
      form: 'Mega', attr: 'Vaccine', traits: ['Holy Beast'],
      dp: 12, cost: 10, evoCost: [2],
      effect: [],
      inherit: []},

    {type:'dgmn', name:'WarGreymon', no: 11, set: 'ST1',
      colors: ['red'], 
      level: 6, 
      form: 'Mega', attr: 'Vaccine', traits: ['Dragonkin'],
      dp: 12, cost: 12, evoCost: 4,
      effect: ['<<Your Turn>> For every 2 digivolution cards this Digimon','has, gain <<Security Attack +1>> .'],
      inherit: []},

    {type:'tamer', name:'Tai Kamiya', no: 12,  set: 'ST1',
      colors: ['red'],
      traits:[],
      cost:4,
      effect:['<<Your Turn>> All of your Digimon get +1000 DP.'],
      inherit: ['<<Security>> Play this card without paying its','memory cost.']},
    {type:'option', name:'Shadow Wing', no: 13, set: 'ST1',
      colors: ['red'],
      traits:[],
      cost: 1,
      effect: ['<<Main>> 1 of your Digimon gets +3000 DP for the turn.'],
      inherit:['<<Security>> All of your Digimon gain','<<Security Attack +1>> until the end of your','next turn.']},
    {type:'option', name: 'Starlight Explosion', no:14, set: 'ST1',
      colors: ['red'],
      traits:[],
      cost: 2,
      effect: ['<<Main>> All of your Security Digimon get +7000 DP until the',"end of your opponent's next turn"],
      inherit: ['<<Security>> All of your Security Digimon get',"+7000 DP for the turn."]},
    { type:'option',name: 'Giga Destroyer', no:15, set: 'ST1',
        colors: ['red'],
        traits: [],
        cost:6,
        effect: ["<<Main>> Delete up to 2 of your opponent's Digimon with","4000 DP or less."],
        inherit: ["<<Security>> Activate this card's <<Main>> effect."] },
    { type:'option',name:'Gaia Force',no:16, set: 'ST1',
      colors: ['red'],
      traits: [],
      cost:8,
      effect: ["<<Main>> Delete 1 of your opponent's Digimon."],
      inherit: ["<<Security>> Activate this card's <<Main>> effect."]
    }],
  ST2: [
    { type:'egg', name:'Tsunomon', no:1, set:'ST2',
      level: 2, colors: ['blue'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<Your Turn>>This Digimon gets +1000 DP when","battling an opponent's Digimon that has no","digivolution cards."]},
  ],
  BT1: BT1,
  BT5: [
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},
    { type:'dgmn', name: 'Weedmon', no:50, set:'BT5', rarity: 'U',
      level: 4, colors: ['green'],
      form: 'Champion', attr: 'Virus', traits: ['Vegetation'],
      dp: 3, cost: 4, evoCost: [1],
      effect: [],
      inherit: ["<<Your Turn>> When this card is trashed due to","activating this Digimon's <<Digi-Burst>>, gain 1","memory."]},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{}
  ],
  BT11: [
    { type:'egg', name:'Yokomon', no:1, set:'BT11',
      level: 2, colors: ['red'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<On Deletion>> If you have a red Tamer in","play, <<Draw 1>>."]},
    { type:'egg', name:'Wanyamon', no:2, set:'BT11',
      level: 2, colors: ['blue'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<When Attacking>> <<Once Per Turn>> If you have a ","blue Tamer in play, <<Draw 1>>."]},
    { type:'egg', name:'Tokomon', no:3, set:'BT11',
      level: 2, colors: ['yellow'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<Your Turn>> <<Once Per Turn>> When you play a","Digimon with [Angel],[Archangel], or [Fallen Angel]","in its traits, <<Draw 1>>."],
      special: ['condensed-inherit']},
    { type:'egg', name:'Tanemon', no:4, set:'BT11',
      level: 2, colors: ['green'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<Your Turn>> <<Once Per Turn>> When you play a green","Tamer, <<Draw 1>>."]},
    { type:'egg', name:'Koromon', no:5, set:'BT11',
      level: 2, colors: ['black'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<Opponent's Turn>> <<Once Per Turn>> When an","opponent's Digimon is deleted, if this Digimon","has [Greymon] in its name, <<Draw 1>>."]},
    { type:'egg', name:'Tsunomon', no:6, set:'BT11',
      level: 2, colors: ['purple'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<Your Turn>> <<Once Per Turn>> When an effect","trashes a card in your hand, this Digimon gets","+1000 DP for the turn."]},
    { type:'dgmn', name: 'Biyomon', no:7, set:'BT11', rarity: 'R',
      level: 3, colors: ['red'],
      form: 'Rookie', traits: ['Bird'],
      dp: 1, cost: 3, evoCost: [0],
      effect: ["<<On Play>> Reveal the top 3 cards of your deck. Add 1 red","Digimon card with [Vaccine] in its traits and 1 red Tamer","card among them to your hand. Place the rest at the","bottom of your deck in any order."],
      inherit: ["<<On Deletion>> If you have a red Tamer in play,","gain 1 memory."]},
    { type:'dgmn', name: 'Bearmon', no:8, set:'BT11',
      level: 3, colors: ['red'],
      form: 'Rookie', attr: 'Vaccine', traits: ['Beast'],
      dp: 2, cost: 3, evoCost: [0],
      effect: [],
      inherit: ["<<Your Turn>> <<Once Per Turn>> When this Digimon's","attack target is switched, this Digimon gets","+3000 DP for the turn."]},
    { type:'dgmn', name: 'Shoutmon + Star Sword', no:9, set:'BT11', rarity: 'C',
      level: 3, colors: ['red','yellow'],
      form: 'Rookie', attr: 'Data', traits: ['Enhancement/Xros Heart'],
      dp: 4, cost: 5, evoCost: [0,1],
      effect: ["This card/Digimon is also treated as if its name is [Shoutmon]","and [Starmons].","<<Material Save 1>>","<<On Play>> 1 of your opponent's Digimon gets -3000 DP for the turn. Then, if","DigiXrosing with 2 cards, delete 1 of your opponent's Digimon with","2000 DP or less.","<<DigiXros -1>> [Shoutmon] X [Starmons]"],
      inherit: ["-"],
      special: ["tall-card-effect","diff-evo-3-2","xros-1","cnd-2","txt-sm-2","name-cnd-5"]},
    { type:'dgmn', name: 'Grizzlymon', no:10, set:'BT11',
      level: 4, colors: ['red'],
      form: 'Champion', attr: 'Vaccine', traits: ['Beast'],
      dp: 5, cost: 5, evoCost: [2],
      effect: ["<<Raid>>"],
      inherit: ["<<Your Turn>> <<Once Per Turn>> When this Digimon's","attack target is switched, this Digimon gets","+3000 DP for the turn."]},
    { type:'dgmn', name: 'Birdramon', no:11, set:'BT11',
      level: 4, colors: ['red'],
      form: 'Champion', attr: 'Vaccine', traits: ['Giant Bird'],
      dp: 5, cost: 5, evoCost: [2],
      effect: ["<<Blocker>>"],
      inherit: ["<<On Deletion>> You may play 1 red Tamer card","with a play cost of 4 or less from your hand","without paying the cost."]},
    { type:'dgmn', name: 'Shoutmon X3', no:12, set:'BT11',
      level: 4, colors: ['red','yellow'],
      form: 'Champion', attr: 'Data', traits: ['Composite/Xros Heart'],
      dp: 6, cost: 7, evoCost: [3,3],
      effect: ["<<Material Save 2>>","<<Start of Your Turn>> By deleting this Digimon, gain 1 memory.","<<On Play>> Reveal the top 3 cards of your deck. Add 2 cards with","[Xros Heart] and/or [Blue Flare] in their traits among them to your hand."," Place the rest at the bottom of your deck in any order.","<<DigiXros -2>> [Shoutmon] X [Ballistamon] X [Dorulumon]"],
      inherit: ["-"],
      special: ["xros-1",'cnd-2',"txt-sm-1","tall-card-effect"]},
    { type:'dgmn', name: 'Garudamon', no:13, set:'BT11', rarity: 'U',
      level: 5, colors: ['red'],
      form: 'Ultimate', attr: 'Vaccine', traits: ['Birdkin'],
      dp: 7, cost: 7, evoCost: [3],
      effect: ["<<Blocker>>"],
      inherit: ["<<On Deletion>> You may play 1 red Tamer card","with a play cost of 4 or less from your hand","without paying the cost."]},
    { type:'dgmn', name: 'GrapLeomon', no:14, set:'BT11', rarity:'U',
      level: 5, colors: ['red'],
      form: 'Ultimate', attr: 'Vaccine', traits: ['Beastkin'],
      dp: 7, cost: 7, evoCost: [3],
      effect: ["<<Raid>>"],
      inherit: ["<<Your Turn>> <<Once Per Turn>> When this Digimon's","attack target is switched, trash the top card of","your opponent's security stack."]},
    { type:'dgmn', name: 'OmniShoutmon', no:15, set:'BT11', rarity:'R',
      level: 5, colors: ['red','blue'],
      form: 'Ultimate', attr: 'Data', traits: ['Dragonkin/Xros Heart'],
      dp: 8, cost: 8, evoCost: [3,3],
      effect: ["When you would DigiXros, the name of this card/Digimon is also treated as","[Shoutmon].","<<When Digivolving>> Delete 1 of your opponent's Digimon with 4000 DP or","less. If [Shoutmon] is in this Digimon's digivolution cards, delete 2 of your","opponent's Digimon with 4000 DP or less instead.","<<On Deletion>> <<Save>>"],
      inherit: ["<<Your Turn>> While this Digimon has [Shoutmon]","in it's name, it gains <<Security Attack +1>>."],
      special: ["spec-evo-4-[Shoutmon]","tall-card-effect","cnd-3","txt-sm-1"]},
    { type:'dgmn', name: 'Phoenixmon', no:16, set:'BT11', rarity:'SR',
      level: 6, colors: ['red'],
      form: 'Mega', attr: 'Vaccine', traits: ['Holy Beast'],
      dp: 11, cost: 11, evoCost: [3],
      effect: ["<<Your Turn>> <<Once Per Turn>> When a card is removed from your opponent's","security stack, you may activate 1 of this Digimon's <<On Deletion>> effects.","<<On Deletion>> You may play 1 red Digimon card with [Avian], [Bird], [Beast],","[Animal], or [Soverign], other than [Sea Animal], in one of its traits and 3000 DP","or less from your hand without paying the cost. For each red Tamer you have in","play, add 2000 to the maximum DP of the card you can play by this effect."],
      inherit: [],
      special: ['no-inherit','txt-sm-2','cnd-3']},
    { type:'dgmn', name: 'Marsmon', no:17, set:'BT11', rarity:'SR',
      level: 6, colors: ['red'],
      form: 'Mega', attr: 'Vaccine', traits: ['Shaman/Olympos XII'],
      dp: 12, cost: 12, evoCost: [4],
      effect: ["<<Raid>>","<<When Digivolving>> <<Blitz>>","<<Your Turn>> <<Once Per Turn>> When one of your Digimon's attack","targets is switched, unsuspend this Digimon and gain","1 memory for each Tamer you have in play."],
      inherit: [],
      special: ['no-inherit']},
    { type:'dgmn', name: 'Shoutmon DX', no:18, set:'BT11', rarity:'R',
      level: 6, colors: ['red','blue'],
      form: 'Mega', attr: 'Data', traits: ['Composite/Xros Heart/Blue Flare'],
      dp: 12, cost: 13, evoCost: [4,3],
      effect: ["The name of this card/Digimon is also treated as [OmniShoutmon]"," and [ZeigGreymon].","<<Material Save 2>>","<<On Play>> Delete 1 of your opponent's Digimon with 8000 DP or less.","1 of your opponent's Digimon can't attack until the end of their turn.","<<End of Attack>> By deleting this Digimon, gain 1 memory.","<<DigiXros -3>> [OmniShoutmon] X [ZeigGreymon]"],
      inherit: [],
      special: ['no-inherit','tall-card-effect',"evo-diff-5-6","cnd-2","txt-sm-2","xros-1"]},
      { type:'dgmn', name: 'Shoutmon X7', no:19, set:'BT11', rarity:'SR',
        level: 6, colors: ['red','white'],
        form: 'Mega', attr: 'Data', traits: ['Composite/Xros Heart/Blue Flare'],
        dp: 13, cost: 14, evoCost: [6,4],
        effect: ["<<Rush>>","<<Material Save 4>>","<<On Play>> Delete 1 of your opponent's Digimon with DP less than or","equal to this Digimon's DP.","<<All Turns>> For every 2 cards in this Digimon's digivolution cards,","it gets +1000 DP.","<<DigiXros -2>> [OmniShoutmon] X [ZeigGreymon] X [Ballistamon]","[Dorulumon] X [Starmons] X [Sparrowmon]"],
        inherit: [],
        special: ['no-inherit','tall-card-effect',"evo-diff-5-6","txt-sm-3","xros-2","evo-color-diff-red-blue"]},

      { type:'dgmn', name: 'Gaomon', no:20, set:'BT11', rarity:'R',
        level: 3, colors: ['blue'],
        form: 'Rookie', attr: 'Data', traits: ['Beast'],
        dp: 1, cost: 3, evoCost: [0],
        effect: ["<<On Play>> Reveal the top 3 cards of your deck. Add 1","Digimon card with [Gaogamon] in its name and 1 blue","Tamer card among them to your hand. Trash the rest."],
        inherit: ["<<When Attacking>> <<Once Per Turn>> If you have a","Tamer in play, return 1 of your opponent's level 3 Digimon to its owner's hand."]},
      { type:'dgmn', name: 'SnowGoblimon', no:21, set:'BT11', rarity:'',
        level: 3, colors: ['blue'],
        form: 'Rookie', attr: 'Virus', traits: ['Demon'],
        dp: 4, cost: 3, evoCost: [0],
        effect: [],
        inherit: ["-"]},
      { type:'dgmn', name: 'Dracomon', no:22, set:'BT11', rarity:'U',
        level: 3, colors: ['blue'],
        form: 'Rookie', attr: 'Data', traits: ['Dragon/Blue Flare'],
        dp: 1, cost: 3, evoCost: [0],
        effect: ["<<Your Turn>> <<Once Per Turn>> When you play another Digimon","with [Dramon] in its name or [Blue Flare] in its","traits, <<Draw 1>>"],
        inherit: ["<<Your Turn>> <<Once Per Turn>> When you play","another Digimon with [Dramon] in its name or","[Blue Flare] in its traits, gain 1 memory."],
        special: ['spec-evo-0-[Bebydomon]']},
    //     {},{},{},{},{},{},{},{},
    // {},{},{},{},{},{},{},{},
    // { type:'dgmn', name: 'AeroVeedramon', no:29, set:'BT11',
    //   level: 5, colors: ['blue'],
    //   form: 'Ultimate', attr: 'Vaccine', traits: ['Holy Dragon'],
    //   dp: 8, cost: 8, evoCost: [3],
    //   effect: ["<<Main>> <<Once Per Turn>> By suspending this Digimon, reveal","the top 3 cards of your deck. Add all blue Tamer cards","among them to your hand. Place the rest at the bottom","of your deck in any order"],
    //   inherit: ["<<When Attacking>> <<Once Per Turn>> Activate 1 of","your [Rina Shinomiya]'s <<On Play>> effects."]},
    // {},{},
    // { type:'dgmn', name: 'UlforceVeedramon', no:32, set:'BT11',
    //   level: 6, colors: ['blue'],
    //   form: 'Mega', attr: 'Vaccine', traits: ['Holy Warrior/Royal Knight'],
    //   dp: 12, cost: 12, evoCost: [4],
    //   effect: ["<<When Digivolving>> You may play 1 blue Tamer card from your hand","without paying the cost.","<<Your Turn>> When you play a blue Tamer, unsuspend this Digimon.","<<Your Turn>> <<Once Per Turn>> When this Digimon becomes","unsuspended, return 1 of your opponent's level 3 or lower Digimon","to its owner's hand. For every blue Tamer you have in play, add 1 to","the max level of the Digimon you can choose with this effect."],
    //   inherit: []},
  ],
  P: P
}

export default CARDS;

/*

    {type:'dgmn', name:'', no: 0,
      colors: [''], 
      level: 0, 
      form: '', attr: '', traits: [''],
      dp: 3, cost: 3,
      effect: [],
      inherit: ['']},

*/

/*

{ type:'',name:'',no:0,
      colors: [],
      traits: [],
      cost:0,
      effect: [""],
      inherit: [""]
    }

    */