import { BT1 } from "./db/BT1.db";
import { BT2 } from "./db/BT2.db";
import { BT11 } from "./db/BT11.db";
import { BT12 } from "./db/BT12.db";
import { BT13 } from "./db/BT13.db";
import { BT3 } from "./db/BT3.db"
import { BT4 } from "./db/BT4.db";
import { BT7 } from "./db/BT7.db";
import { BT9 } from "./db/BT9.db";
import { EX4 } from "./db/EX4.db";
import { P } from "./db/P.db";
import { ST14 } from "./db/ST14.db";

const CARDS = {
  ST1: [
    {type: 'egg',name:'Koromon', no: 1, set: 'ST1',
      colors: ['red'],
      level: 2,
    form: 'In-Training', traits: ['Lesser'],
    inherit: ['<<Your Turn>> While this Digimon has 4 or more','digivolution cards, it gets +1000 DP.']},

    {type: 'dgmn',name:'Biyomon', no: 2, set: 'ST1',
      colors: ['red','black'], 
      level: 3, 
      form: 'Rookie', attr: 'Vaccine', traits: ['Bird'],
      dp: 3, cost: 2, evoCost: [0],
      effect: [],
      inherit: ['-'] },

    {type:'dgmn', name:'Agumon', no: 3, set: 'ST1',
      colors: ['red'], 
      level: 3, 
      form: 'Rookie', attr: 'Vaccine', traits: ['Reptile'],
      dp: 2, cost: 3, evoCost: [0],
      effect: [],
      inherit: ['<<Your Turn>> This Digimon gets +1000 DP.'] },

    {type:'dgmn', name:'Dracomon', no: 4, set: 'ST1',
      colors: ['red'], 
      level: 3, 
      form: 'Rookie', attr: 'Data', traits: ['Dragon'],
      dp: 4, cost: 3, evoCost: [0],
      effect: [],
      inherit: ['-'] },

    {type:'dgmn', name:'Birdramon', no: 5, set: 'ST1',
      colors: ['red'], 
      level: 4, 
      form: 'Champion', attr: 'Vaccine', traits: ['Giant Bird'],
      dp: 5, cost: 4, evoCost: [2],
      effect: [],
      inherit: ['-']},
    {type:'dgmn', name:'Coredramon', no: 6, set: 'ST1',
      colors: ['red'], 
      level: 4, 
      form: 'Champion', attr: 'Virus', traits: ['Dragon'],
      dp: 6, cost: 5, evoCost: [2],
      effect: ['<<Blocker>>','<<When Attacking>> Lose 2 memory.'],
      inherit: ['-']},
    {type:'dgmn', name:'Greymon', no: 7, set: 'ST1',
      colors: ['red'], evoCost: [2],
      level: 4, 
      form: 'Champion', attr: 'Vaccine', traits: ['Dinosaur'],
      dp: 4, cost: 5, evoCost: [2],
      effect: [],
      inherit: ['<<Security Attack +1>>']},

    {type:'dgmn', name:'Garudamon', no: 8, set: 'ST1',
      colors: ['red'], 
      level: 5, 
      form: 'Ultimate', attr: 'Vaccine', traits: ['Birdkin'],
      dp: 7, cost: 6, evoCost: [3],
      effect: ['<<When Digivolving>> 1 of your Digimon gets +3000 DP for','the turn.'],
      inherit: ['-']},

    {type:'dgmn', name:'MetalGreymon', no: 9, set: 'ST1',
      colors: ['red'], 
      level: 5, 
      form: 'Ultimate', attr: 'Vaccine', traits: ['Cyborg'],
      dp: 7, cost: 7, evoCost: [3],
      effect: [],
      inherit: ['<<Your Turn>> When this Digimon is blocked, gain','3 memory.']},

    {type:'dgmn', name:'Phoenixmon', no: 10, set: 'ST1',
      colors: ['red'], 
      level: 6, 
      form: 'Mega', attr: 'Vaccine', traits: ['Holy Beast'],
      dp: 12, cost: 10, evoCost: [2],
      effect: [],
      inherit: []},

    {type:'dgmn', name:'WarGreymon', no: 11, set: 'ST1',
      colors: ['red'], 
      level: 6, 
      form: 'Mega', attr: 'Vaccine', traits: ['Dragonkin'],
      dp: 12, cost: 12, evoCost: 4,
      effect: ['<<Your Turn>> For every 2 digivolution cards this Digimon','has, gain <<Security Attack +1>> .'],
      inherit: []},

    {type:'tamer', name:'Tai Kamiya', no: 12,  set: 'ST1',
      colors: ['red'],
      traits:[],
      cost:4,
      effect:['<<Your Turn>> All of your Digimon get +1000 DP.'],
      inherit: ['<<Security>> Play this card without paying its','memory cost.']},
    {type:'option', name:'Shadow Wing', no: 13, set: 'ST1',
      colors: ['red'],
      traits:[],
      cost: 1,
      effect: ['<<Main>> 1 of your Digimon gets +3000 DP for the turn.'],
      inherit:['<<Security>> All of your Digimon gain','<<Security Attack +1>> until the end of your','next turn.']},
    {type:'option', name: 'Starlight Explosion', no:14, set: 'ST1',
      colors: ['red'],
      traits:[],
      cost: 2,
      effect: ['<<Main>> All of your Security Digimon get +7000 DP until the',"end of your opponent's next turn"],
      inherit: ['<<Security>> All of your Security Digimon get',"+7000 DP for the turn."]},
    { type:'option',name: 'Giga Destroyer', no:15, set: 'ST1',
        colors: ['red'],
        traits: [],
        cost:6,
        effect: ["<<Main>> Delete up to 2 of your opponent's Digimon with","4000 DP or less."],
        inherit: ["<<Security>> Activate this card's <<Main>> effect."] },
    { type:'option',name:'Gaia Force',no:16, set: 'ST1',
      colors: ['red'],
      traits: [],
      cost:8,
      effect: ["<<Main>> Delete 1 of your opponent's Digimon."],
      inherit: ["<<Security>> Activate this card's <<Main>> effect."]
    }],
  ST2: [
    { type:'egg', name:'Tsunomon', no:1, set:'ST2',
      level: 2, colors: ['blue'],
      form: 'In-Training', traits: ['Lesser'],
      inherit: ["<<Your Turn>>This Digimon gets +1000 DP when","battling an opponent's Digimon that has no","digivolution cards."]},
  ],
  ST14: ST14,
  BT1: BT1,
  BT2: BT2,
  BT3: BT3,
  BT4: BT4,
  BT5: [
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},
    { type:'dgmn', name: 'Weedmon', no:50, set:'BT5', rarity: 'U',
      level: 4, colors: ['green'],
      form: 'Champion', attr: 'Virus', traits: ['Vegetation'],
      dp: 3, cost: 4, evoCost: [1],
      effect: [],
      inherit: ["<<Your Turn>> When this card is trashed due to","activating this Digimon's <<Digi-Burst>>, gain 1","memory."]},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{},{},{},{},{},{},{},{},{},
    {},{}
  ],
  BT7: BT7,
  BT9: BT9,
  BT11: BT11,
  BT12: BT12,
  BT13: BT13,
  EX4: EX4,
  P: P
}

export default CARDS;
