export const P = [
  {},{},{},{},{},{},{},{},{},{},
  {},{},{},{},{},{},
  { type:'dgmn', name: 'DemiDevimon', no:17, set:'P', rarity:'P',
    level: 3, colors: ['purple'],
    form: 'Rookie', attr: 'Virus', traits: ['Evil'],
    dp: 2, cost: 3, evoCost: [0],
    effect: ["<<On Play>> Trash the top 2 cards of your deck."],
    inherit: ["-"]},{},{},{},
  {},{},{},{},{},{},{},{},{},{},
  {},{},{},
  { type:'dgmn', name: 'DemiDevimon', no:34, set:'P', rarity:'P',
    level: 3, colors: ['purple'],
    form: 'Rookie', attr: 'Virus', traits: ['Evil'],
    dp: 2, cost: 3, evoCost: [0],
    effect: [],
    inherit: ["<<On Deletion>> If ou have 7 or more Digimon","cards with [Devimon] in their name in your","trash, you may play 1 [DanDevimon] from your","trash without paying its memory cost"]},{},{},
  { type: 'option', name:'Yellow Memory Boost!', no:37, set: 'P', rarity: 'SR',
    colors: ['yellow'],
    traits:[],
    cost: 3,
    effect: ["<<Main>> Reveal the top 4 cards of your deck. Add 1 yellow Digimon card","among them to your hand. Place the remaining cards at the bottom","of your deck in any order. Then, place this card in your battle area.","<<Main>> <<Delay>>","• Gain 2 memory."],
    inherit: ["<<Security>> Place this card in its owner's battle area."],
    modClasses: ['effect-cnd-2','effect-sm-1']
  },
  { type: 'option', name:'Green Memory Boost!', no:38, set: 'P', rarity: 'SR',
    colors: ['green'],
    traits:[],
    cost: 3,
    effect: ["<<Main>> Reveal the top 4 cards of your deck. Add 1 green Digimon card","among them to your hand. Place the remaining cards at the bottom","of your deck in any order. Then, place this card in your battle area.","<<Main>> <<Delay>>","• Gain 2 memory."],
    inherit: ["<<Security>> Place this card in its owner's battle area."],
    special: ["condensed-inherit","super-condensed-card-effect"],
    modClasses: ['effect-cnd-2','effect-sm-1']
  },{},{},
  {},{},{},{},{},{},{},{},{},{},
  {},{},{},{},{},{},{},{},{},{},
  {},{},{},{},{},{},{},{},{},{},
  {},{},{},{},{},{},{},{},{},{},
]
